version: "3.7"

services:
    app:
        container_name: docker-mongo
        restart: always
        build: .
        ports: 
            - '1128:1128'
        depends_on:
            - 'mongodb'
    mongodb:
        container_name: mongo_compose
        image: mongo:latest

    proxy:
        container_name: proxy
        restart: alwaysbuild: ./proxy
        ports:
            - '3000:3000'
